runtime: nodejs18

env_variables:
    OPENAI_API_KEY: "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"
    NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: "G-E7KWEZDG7V"
    GOOGLE_CLIENT_ID: "146773869153-c0eq8orpska1j6aaf77spqjnbj2ug4ek.apps.googleusercontent.com"
    GOOGLE_CLIENT_SECRET: "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"
    NEXTAUTH_URL: "http://localhost:3000"
    JWT_SECRET: "MMPkRzohnnPEa56FRK80JIQmgI0z2434d9xHdHispmc="
    GITHUB_ID: "Iv1.19db3239c79c7f31"
    GITHUB_SECRET: "54cd1720a2ebff36a0c540c9b4558c9459df7997"

    MONGODB_URI: "mongodb+srv://Project2Product:NhQdZIns3FiLTB9B@project2product-cluster.ov0lxht.mongodb.net/project2product?retryWrites=true&w=majority"

    SMTP_HOST: "smtp.mailtrap.io"
    SMTP_PORT: "2525"
    SMTP_USER: "385c0f2a908ba0"
    SMTP_PASSWORD: "7e393b5580a2d6"
    SMTP_FROM_NAME: "Project2Product"
    SMTP_FROM_EMAIL: "no-reply@musixverse.com"

    NEXT_PUBLIC_STRIPE_API_KEY: "pk_test_51MjzfvSAnJ9FcxzQLFTScP7B97ZHKVAThIxbxO3fBr55i1RAE0MSGvuOH2cD9E5qmkIEON32dtjCv9lFsl9S5FwN00NA45xYMD"
    STRIPE_SECRET_KEY: "sk_test_51MjzfvSAnJ9FcxzQcX6AUlfw1NFMlCkiqdD8euBSrwNLlNAfMatRFuWs5PEeSDTFd0U64gvsw1XH4FPD7wiupO2R00yIf4MdkE"

    STRIPE_WEBHOOK_SECRET: "whsec_e296c374a7a6f69e42919585acdccfd64a20a75fbcf0b4c95bf1d4b3d273f8cf"
