export const NEW_BUG_REPORT_REQUEST = "NEW_BUG_REPORT_REQUEST";
export const NEW_BUG_REPORT_SUCCESS = "NEW_BUG_REPORT_SUCCESS";
export const NEW_BUG_REPORT_FAIL = "NEW_BUG_REPORT_FAIL";

export const ADMIN_GET_BUG_REPORTS_REQUEST = "ADMIN_GET_BUG_REPORTS_REQUEST";
export const ADMIN_GET_BUG_REPORTS_SUCCESS = "ADMIN_GET_BUG_REPORTS_SUCCESS";
export const ADMIN_GET_BUG_REPORTS_FAIL = "ADMIN_GET_BUG_REPORTS_FAIL";

export const ADMIN_DELETE_BUG_REPORT_REQUEST = "ADMIN_DELETE_BUG_REPORT_REQUEST";
export const ADMIN_DELETE_BUG_REPORT_SUCCESS = "ADMIN_DELETE_BUG_REPORT_SUCCESS";
export const ADMIN_DELETE_BUG_REPORT_RESET = "ADMIN_DELETE_BUG_REPORT_RESET";
export const ADMIN_DELETE_BUG_REPORT_FAIL = "ADMIN_DELETE_BUG_REPORT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
