export const NEW_CONTACT_US_MESSAGE_REQUEST = "NEW_CONTACT_US_MESSAGE_REQUEST";
export const NEW_CONTACT_US_MESSAGE_SUCCESS = "NEW_CONTACT_US_MESSAGE_SUCCESS";
export const NEW_CONTACT_US_MESSAGE_FAIL = "NEW_CONTACT_US_MESSAGE_FAIL";

export const ADMIN_GET_CONTACT_US_MESSAGES_REQUEST = "ADMIN_GET_CONTACT_US_MESSAGES_REQUEST";
export const ADMIN_GET_CONTACT_US_MESSAGES_SUCCESS = "ADMIN_GET_CONTACT_US_MESSAGES_SUCCESS";
export const ADMIN_GET_CONTACT_US_MESSAGES_FAIL = "ADMIN_GET_CONTACT_US_MESSAGES_FAIL";

export const ADMIN_DELETE_CONTACT_US_MESSAGE_REQUEST = "ADMIN_DELETE_CONTACT_US_MESSAGE_REQUEST";
export const ADMIN_DELETE_CONTACT_US_MESSAGE_SUCCESS = "ADMIN_DELETE_CONTACT_US_MESSAGE_SUCCESS";
export const ADMIN_DELETE_CONTACT_US_MESSAGE_RESET = "ADMIN_DELETE_CONTACT_US_MESSAGE_RESET";
export const ADMIN_DELETE_CONTACT_US_MESSAGE_FAIL = "ADMIN_DELETE_CONTACT_US_MESSAGE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
