export const NEW_FEATURE_REQUEST_REQUEST = "NEW_FEATURE_REQUEST_REQUEST";
export const NEW_FEATURE_REQUEST_SUCCESS = "NEW_FEATURE_REQUEST_SUCCESS";
export const NEW_FEATURE_REQUEST_FAIL = "NEW_FEATURE_REQUEST_FAIL";

export const ADMIN_GET_FEATURE_REQUESTS_REQUEST = "ADMIN_GET_FEATURE_REQUESTS_REQUEST";
export const ADMIN_GET_FEATURE_REQUESTS_SUCCESS = "ADMIN_GET_FEATURE_REQUESTS_SUCCESS";
export const ADMIN_GET_FEATURE_REQUESTS_FAIL = "ADMIN_GET_FEATURE_REQUESTS_FAIL";

export const ADMIN_DELETE_FEATURE_REQUEST_REQUEST = "ADMIN_DELETE_FEATURE_REQUEST_REQUEST";
export const ADMIN_DELETE_FEATURE_REQUEST_SUCCESS = "ADMIN_DELETE_FEATURE_REQUEST_SUCCESS";
export const ADMIN_DELETE_FEATURE_REQUEST_RESET = "ADMIN_DELETE_FEATURE_REQUEST_RESET";
export const ADMIN_DELETE_FEATURE_REQUEST_FAIL = "ADMIN_DELETE_FEATURE_REQUEST_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
