export const ALL_GENERATED_RESPONSES_SUCCESS = "ALL_GENERATED_RESPONSES_SUCCESS";
export const ALL_GENERATED_RESPONSES_FAIL = "ALL_GENERATED_RESPONSES_FAIL";

export const ADMIN_DELETE_GENERATED_RESPONSE_REQUEST = "ADMIN_DELETE_GENERATED_RESPONSE_REQUEST";
export const ADMIN_DELETE_GENERATED_RESPONSE_SUCCESS = "ADMIN_DELETE_GENERATED_RESPONSE_SUCCESS";
export const ADMIN_DELETE_GENERATED_RESPONSE_RESET = "ADMIN_DELETE_GENERATED_RESPONSE_RESET";
export const ADMIN_DELETE_GENERATED_RESPONSE_FAIL = "ADMIN_DELETE_GENERATED_RESPONSE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
