export const NEW_IDEA_SWIPE_REQUEST = "NEW_IDEA_SWIPE_REQUEST";
export const NEW_IDEA_SWIPE_SUCCESS = "NEW_IDEA_SWIPE_SUCCESS";
export const NEW_IDEA_SWIPE_FAIL = "NEW_IDEA_SWIPE_FAIL";

export const ALL_IDEA_SWIPES_SUCCESS = "ALL_IDEA_SWIPES_SUCCESS";
export const ALL_IDEA_SWIPES_FAIL = "ALL_IDEA_SWIPES_FAIL";

export const VOTE_IDEA_REQUEST = "VOTE_IDEA_REQUEST";
export const VOTE_IDEA_SUCCESS = "VOTE_IDEA_SUCCESS";
export const VOTE_IDEA_FAIL = "VOTE_IDEA_FAIL";

export const VOTE_SECTION_IDEA_REQUEST = "VOTE_SECTION_IDEA_REQUEST";
export const VOTE_SECTION_IDEA_SUCCESS = "VOTE_SECTION_IDEA_SUCCESS";
export const VOTE_SECTION_IDEA_FAIL = "VOTE_SECTION_IDEA_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
