export const NEW_IDEA_SEARCH_REQUEST = "NEW_IDEA_SEARCH_REQUEST";
export const NEW_IDEA_SEARCH_SUCCESS = "NEW_IDEA_SEARCH_SUCCESS";
export const NEW_IDEA_SEARCH_FAIL = "NEW_IDEA_SEARCH_FAIL";

export const ALL_IDEAS_SUCCESS = "ALL_IDEAS_SUCCESS";
export const ALL_IDEAS_FAIL = "ALL_IDEAS_FAIL";

export const MY_IDEAS_SUCCESS = "MY_IDEAS_SUCCESS";
export const MY_IDEAS_FAIL = "MY_IDEAS_FAIL";

export const IDEA_DETAILS_SUCCESS = "IDEA_DETAILS_SUCCESS";
export const IDEA_DETAILS_FAIL = "IDEA_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
