export const NEW_NEWSLETTER_REQUEST = "NEW_NEWSLETTER_REQUEST";
export const NEW_NEWSLETTER_SUCCESS = "NEW_NEWSLETTER_SUCCESS";
export const NEW_NEWSLETTER_FAIL = "NEW_NEWSLETTER_FAIL";

export const ADMIN_GET_NEWSLETTERS_REQUEST = "ADMIN_GET_NEWSLETTERS_REQUEST";
export const ADMIN_GET_NEWSLETTERS_SUCCESS = "ADMIN_GET_NEWSLETTERS_SUCCESS";
export const ADMIN_GET_NEWSLETTERS_FAIL = "ADMIN_GET_NEWSLETTERS_FAIL";

export const ADMIN_DELETE_NEWSLETTER_REQUEST = "ADMIN_DELETE_NEWSLETTER_REQUEST";
export const ADMIN_DELETE_NEWSLETTER_SUCCESS = "ADMIN_DELETE_NEWSLETTER_SUCCESS";
export const ADMIN_DELETE_NEWSLETTER_RESET = "ADMIN_DELETE_NEWSLETTER_RESET";
export const ADMIN_DELETE_NEWSLETTER_FAIL = "ADMIN_DELETE_NEWSLETTER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
