export const NEW_PROJECT_SEARCH_REQUEST = "NEW_PROJECT_SEARCH_REQUEST";
export const NEW_PROJECT_SEARCH_SUCCESS = "NEW_PROJECT_SEARCH_SUCCESS";
export const NEW_PROJECT_SEARCH_FAIL = "NEW_PROJECT_SEARCH_FAIL";

export const ALL_PROJECTS_SUCCESS = "ALL_PROJECTS_SUCCESS";
export const ALL_PROJECTS_FAIL = "ALL_PROJECTS_FAIL";

export const MY_PROJECTS_SUCCESS = "MY_PROJECTS_SUCCESS";
export const MY_PROJECTS_FAIL = "MY_PROJECTS_FAIL";

export const PROJECT_DETAILS_SUCCESS = "PROJECT_DETAILS_SUCCESS";
export const PROJECT_DETAILS_FAIL = "PROJECT_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
