export const ALL_PROJECTS_SUCCESS = "ALL_PROJECTS_SUCCESS";
export const ALL_PROJECTS_FAIL = "ALL_PROJECTS_FAIL";

export const PROJECT_DETAILS_SUCCESS = "PROJECT_DETAILS_SUCCESS";
export const PROJECT_DETAILS_FAIL = "PROJECT_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
