export const CHECK_SUBSCRIPTION_REQUEST = "CHECK_SUBSCRIPTION_REQUEST";
export const CHECK_SUBSCRIPTION_SUCCESS = "CHECK_SUBSCRIPTION_SUCCESS";
export const CHECK_SUBSCRIPTION_RESET = "CHECK_SUBSCRIPTION_RESET";
export const CHECK_SUBSCRIPTION_FAIL = "CHECK_SUBSCRIPTION_FAIL";

export const MY_SUBSCRIPTION_SUCCESS = "MY_SUBSCRIPTION_SUCCESS";
export const MY_SUBSCRIPTION_FAIL = "MY_SUBSCRIPTION_FAIL";

export const ADMIN_GET_SUBSCRIPTIONS_REQUEST = "ADMIN_GET_SUBSCRIPTIONS_REQUEST";
export const ADMIN_GET_SUBSCRIPTIONS_SUCCESS = "ADMIN_GET_SUBSCRIPTIONS_SUCCESS";
export const ADMIN_GET_SUBSCRIPTIONS_FAIL = "ADMIN_GET_SUBSCRIPTIONS_FAIL";

export const ADMIN_DELETE_SUBSCRIPTION_REQUEST = "ADMIN_DELETE_SUBSCRIPTION_REQUEST";
export const ADMIN_DELETE_SUBSCRIPTION_SUCCESS = "ADMIN_DELETE_SUBSCRIPTION_SUCCESS";
export const ADMIN_DELETE_SUBSCRIPTION_RESET = "ADMIN_DELETE_SUBSCRIPTION_RESET";
export const ADMIN_DELETE_SUBSCRIPTION_FAIL = "ADMIN_DELETE_SUBSCRIPTION_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
