export const CHECK_SUBSCRIPTION_REQUEST = "CHECK_SUBSCRIPTION_REQUEST";
export const CHECK_SUBSCRIPTION_SUCCESS = "CHECK_SUBSCRIPTION_SUCCESS";
export const CHECK_SUBSCRIPTION_RESET = "CHECK_SUBSCRIPTION_RESET";
export const CHECK_SUBSCRIPTION_FAIL = "CHECK_SUBSCRIPTION_FAIL";

export const MY_SUBSCRIPTION_SUCCESS = "MY_SUBSCRIPTION_SUCCESS";
export const MY_SUBSCRIPTION_FAIL = "MY_SUBSCRIPTION_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
