export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const ADMIN_GET_ALL_USERS_REQUEST = "ADMIN_GET_ALL_USERS_REQUEST";
export const ADMIN_GET_ALL_USERS_SUCCESS = "ADMIN_GET_ALL_USERS_SUCCESS";
export const ADMIN_GET_ALL_USERS_FAIL = "ADMIN_GET_ALL_USERS_FAIL";

export const ADMIN_GET_USER_DETAILS_REQUEST = "ADMIN_GET_USER_DETAILS_REQUEST";
export const ADMIN_GET_USER_DETAILS_SUCCESS = "ADMIN_GET_USER_DETAILS_SUCCESS";
export const ADMIN_GET_USER_DETAILS_FAIL = "ADMIN_GET_USER_DETAILS_FAIL";

export const ADMIN_UPDATE_USER_DETAILS_REQUEST = "ADMIN_UPDATE_USER_DETAILS_REQUEST";
export const ADMIN_UPDATE_USER_DETAILS_SUCCESS = "ADMIN_UPDATE_USER_DETAILS_SUCCESS";
export const ADMIN_UPDATE_USER_DETAILS_RESET = "ADMIN_UPDATE_USER_DETAILS_RESET";
export const ADMIN_UPDATE_USER_DETAILS_FAIL = "ADMIN_UPDATE_USER_DETAILS_FAIL";

export const ADMIN_DELETE_USER_REQUEST = "ADMIN_DELETE_USER_REQUEST";
export const ADMIN_DELETE_USER_SUCCESS = "ADMIN_DELETE_USER_SUCCESS";
export const ADMIN_DELETE_USER_RESET = "ADMIN_DELETE_USER_RESET";
export const ADMIN_DELETE_USER_FAIL = "ADMIN_DELETE_USER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
